//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlRootAttribute("matchdata", Namespace="", IsNullable=false)]
public partial class matchdataType {
    
    private string refereeField;
    
    private matchType matchField;
    
    private securityType[] securityField;
    
    private string matchidField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string referee {
        get {
            return this.refereeField;
        }
        set {
            this.refereeField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public matchType match {
        get {
            return this.matchField;
        }
        set {
            this.matchField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute("security", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public securityType[] security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttributeAttribute()]
    public string matchid {
        get {
            return this.matchidField;
        }
        set {
            this.matchidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class matchType {
    
    private string homeField;
    
    private string awayField;
    
    private string stadiumField;
    
    private string matchdayField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string home {
        get {
            return this.homeField;
        }
        set {
            this.homeField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string away {
        get {
            return this.awayField;
        }
        set {
            this.awayField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stadium {
        get {
            return this.stadiumField;
        }
        set {
            this.stadiumField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string matchday {
        get {
            return this.matchdayField;
        }
        set {
            this.matchdayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class securityType {
    
    private string contractorField;
    
    private string priceInPoundsField;
    
    private string[] sectorField;
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contractor {
        get {
            return this.contractorField;
        }
        set {
            this.contractorField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string priceInPounds {
        get {
            return this.priceInPoundsField;
        }
        set {
            this.priceInPoundsField = value;
        }
    }
    
    /// <remarks/>
    [XmlElementAttribute("sector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] sector {
        get {
            return this.sectorField;
        }
        set {
            this.sectorField = value;
        }
    }
}
